services:
  - type: web
    name: blockchain-vote
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: RENDER_EXTERNAL_URL
        fromContext: render_external_url
      - key: FACTORY_ADDRESS
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: RPC_URL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_TENANT_ID
        value: common
